<a href="https://colab.research.google.com/github/FelipeGaigher/Bingo/blob/main/Bingo_Online.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Bingo Online em Hexadecimal.

### Desenvolvimento das funções.


In [3]:
# BIBLIOTECAS:
import numpy
from numpy.random import default_rng
from random import randint
import random
import pandas

In [5]:
"""
FUNÇÃO: Criar Cartela (4 x 4), com a seguintes características:
1: Números Aleatórios: Intervalo entre [16, 159];
2: Criar em Decimal (Base 10: 0, 1, 2, 3, 4, 5, 6, 7, 8 e 9)
3: NÃO pode ter NÚMEROS REPETIDOS na cartela. Caso seja sorteado um número repetido,
o sorteio deve ser refeito até sair um número que ainda não foi sorteado na partida.
3: PARÂMETRO NOMINAL: Inserir (de forma OPCIONAL) o Nome do Jogador na Cartela.
"""
#Gerar cartela sem repetição:
linha=4
coluna=4

def gerarCartela():
  while True:
    cartela = numpy.zeros((linha,coluna), dtype =int)
    cartela[:,0] = numpy.random.randint(16, 160,linha, dtype=int)
    cartela[:,1] = numpy.random.randint(16, 160,linha, dtype=int)
    cartela[:,2] = numpy.random.randint(16, 160,linha, dtype=int)
    cartela[:,3] = numpy.random.randint(16, 160,linha, dtype=int)
    cartelaConcatenada = numpy.concatenate(cartela)
    if len(cartelaConcatenada) == len(set(cartelaConcatenada)):
        break
  return cartela
# Transformar para resultado da função
cartelaSemRepeticao1 = gerarCartela()
cartelaSemRepeticao2 = gerarCartela()
cartelaSemRepeticao3 = gerarCartela()
print(f'{cartelaSemRepeticao1}\n\n {cartelaSemRepeticao2}\n\n {cartelaSemRepeticao3}')

[[ 52  60 154 152]
 [ 44 101 126  93]
 [ 24  65  79 104]
 [ 70  59  87  91]]

 [[110 144 157 155]
 [139 150  68  35]
 [ 87 154  98 124]
 [116  53 120  52]]

 [[136 149 147  46]
 [131  93  28  23]
 [ 55  48  99  81]
 [ 82  90  87 113]]


In [6]:
# FUNÇÃO: Conversão Decimal-Hexadecimal ()
#Cartela1
def converteHex(cartelaSemRepeticao):
    cartelaHex1 = []
    for posicaoLinhas in range(4):
        for posicaoColunas in range(4):
            cartelaHex1.append((hex(cartelaSemRepeticao1[posicaoLinhas, posicaoColunas])[2:].upper()))
        cartelaHex4x4 = [cartelaHex1[0:4], cartelaHex1[4:8], cartelaHex1[8:12], cartelaHex1[12:]]
    return cartelaHex4x4
cartelaHex1 = (converteHex(cartelaSemRepeticao1))
print(cartelaHex1)

#Cartela2
def converteHex2(cartelaSemRepeticao):
    cartelaHex2 = []
    for posicaoLinhas in range(4):
        for posicaoColunas in range(4):
            cartelaHex2.append((hex(cartelaSemRepeticao2[posicaoLinhas, posicaoColunas])[2:].upper()))
        cartelaHex4x4 = [cartelaHex2[0:4], cartelaHex2[4:8], cartelaHex2[8:12], cartelaHex2[12:]]
    return cartelaHex4x4
cartelaHex2 = (converteHex2(cartelaSemRepeticao1))
print(cartelaHex2)

#Cartela3
def converteHex3(cartelaSemRepeticao):
    cartelaHex3 = []
    for posicaoLinhas in range(4):
        for posicaoColunas in range(4):
            cartelaHex3.append((hex(cartelaSemRepeticao3[posicaoLinhas, posicaoColunas])[2:].upper()))
        cartelaHex4x4 = [cartelaHex3[0:4], cartelaHex3[4:8], cartelaHex3[8:12], cartelaHex3[12:]]
    return cartelaHex4x4
cartelaHex3 = (converteHex3(cartelaSemRepeticao1))
print(cartelaHex3)


[['34', '3C', '9A', '98'], ['2C', '65', '7E', '5D'], ['18', '41', '4F', '68'], ['46', '3B', '57', '5B']]
[['6E', '90', '9D', '9B'], ['8B', '96', '44', '23'], ['57', '9A', '62', '7C'], ['74', '35', '78', '34']]
[['88', '95', '93', '2E'], ['83', '5D', '1C', '17'], ['37', '30', '63', '51'], ['52', '5A', '57', '71']]


In [7]:
#Criação de uma lista com valores das pedras sorteadas
lista= [16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,
              122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159]
vetorPedrasSorteadas = []

In [10]:
# FUNÇÃO: Conferir Pedra
#FUNÇÃO: Sortear uma (1) Pedra: RANDOM DECIMAL: [16, 159]
def sorteioPedra(lista):
  rng = default_rng()
  listaPedra = rng.choice(range(0,len(lista)), replace = False)
  index = 0
  while (index < 1):
    pedra = lista[listaPedra]
    del(lista[listaPedra])
    pedra
    index += 1
    vetorPedrasSorteadas.append(pedra)
  return pedra
pedraSorteada = sorteioPedra(lista)
print(f'pedraSorteada: \n{pedraSorteada}')
# print(f'lista: \n{lista}')
print(f'Vetor da Pedra: {vetorPedrasSorteadas}')

#Converter pedra sorteada em hexadecimal
def converterHex(pedraSorteada):
  pedraHex = hex(pedraSorteada)[2:].upper()
  return pedraHex
pedraHex = converterHex(pedraSorteada)
print(pedraHex)

pedraSorteada: 
45
Vetor da Pedra: [116, 77, 45]
2D


In [11]:
# FUNÇÃO: Exibir Cartela Hexadecimal: 4 x 4
# FUNÇÃO: Exibir Cartela Hexadecimal: 4 x 4
#FUNÇÕES DAS CARTELAS COM PANDAS:
def cartelaPandas1():
  cartelaPandas1 = cartelaHex1
  cartelaPandas1 = pandas.DataFrame(cartelaPandas1, 
                      index=['Bingo Geek', '', '', ''], 
                      columns=['', '', '', ''])
  return cartelaPandas1
cartelaPandas1 = cartelaPandas1()
cartelaPandas1

def cartelaPandas2():
  cartelaPandas2 = cartelaHex2
  cartelaPandas2 = pandas.DataFrame(cartelaPandas2, 
                      index=['Bingo Geek', '', '', ''], 
                      columns=['', '', '', ''])
  return cartelaPandas2
cartelaPandas2 = cartelaPandas2()
cartelaPandas2

def cartelaPandas3():
  cartelaPandas3 = cartelaHex3
  cartelaPandas3 = pandas.DataFrame(cartelaPandas3, 
                      index=['Bingo Geek', '', '', ''], 
                      columns=['', '', '', ''])
  return cartelaPandas3
cartelaPandas3 = cartelaPandas3()
cartelaPandas3

print(f'{cartelaPandas1}\n\n {cartelaPandas2}\n\n {cartelaPandas3}')

                          
Bingo Geek  34  3C  9A  98
            2C  65  7E  5D
            18  41  4F  68
            46  3B  57  5B

                           
Bingo Geek  6E  90  9D  9B
            8B  96  44  23
            57  9A  62  7C
            74  35  78  34

                           
Bingo Geek  88  95  93  2E
            83  5D  1C  17
            37  30  63  51
            52  5A  57  71


In [12]:
#Variavel de pontuação:
ponto1 = []
ponto2 = []
ponto3 = []

In [23]:
# FUNÇÃO: Exibir Pontuação

pedraSorteada = sorteioPedra(lista)
pedraHex = converterHex(pedraSorteada)
print(pedraHex)

print(f'Vetor da Pedra: {vetorPedrasSorteadas}')
# FUNÇÃO: Exibir Pontuação
def pontuacao1(pedraSorteada):
  ponto = 0
  listaPedra = pedraSorteada
  for posl in range(4):
        for posc in range(4):
          if (listaPedra == cartelaSemRepeticao1[posl, posc]):
            ponto += 1
  ponto1.append(ponto)
  return sum(ponto1)

print('jogador1',pontuacao1(pedraSorteada))

#Função: Pontuação2
def pontuacao2(pedraSorteada):
  ponto = 0
  listaPedra = pedraSorteada
  for posl in range(4):
        for posc in range(4):
          if (listaPedra == cartelaSemRepeticao2[posl, posc]):
            ponto += 1
  ponto2.append(ponto)
  return sum(ponto2)
print('jogador2',pontuacao2(pedraSorteada))

# Pontuação3
def pontuacao3(pedraSorteada):
  ponto = 0
  listaPedra = pedraSorteada
  for posl in range(4):
        for posc in range(4):
          if (listaPedra == cartelaSemRepeticao3[posl, posc]):
            ponto += 1
  ponto3.append(ponto)
  return sum(ponto3)

print('jogador3',pontuacao3(pedraSorteada))

6B
Vetor da Pedra: [116, 77, 45, 94, 40, 148, 21, 109, 64, 123, 151, 100, 55, 107]
jogador1 0
jogador2 0
jogador3 1


In [24]:
# FUNÇÃO: Exibir Vencedor/Premiação
# Premiação: R$ 100 - Cada pedra sorteada antes do Vencedor + R$ Maior Número (Decimal) da Cartela.

def premiacao1(vetorPedrasSorteadas, cartelaSemRepeticao1):
  valorMax1 = numpy.concatenate(cartelaSemRepeticao1)
  print(max(valorMax1))
  premio = 100 - len(vetorPedrasSorteadas) + max(valorMax1)
  return premio
print(premiacao1(vetorPedrasSorteadas, cartelaSemRepeticao1))
def premiacao2(vetorPedrasSorteadas, cartelaSemRepeticao2):
  valorMax2 = numpy.concatenate(cartelaSemRepeticao2)
  print(max(valorMax2))
  premio = 100 - len(vetorPedrasSorteadas) + max(valorMax2)
  return premio
print(premiacao2(vetorPedrasSorteadas, cartelaSemRepeticao2))
def premiacao3(vetorPedrasSorteadas, cartelaSemRepeticao3):
  valorMax3 = numpy.concatenate(cartelaSemRepeticao3)
  print(max(valorMax3))
  premio = 100 - len(vetorPedrasSorteadas) + max(valorMax3)
  return premio
print(premiacao3(vetorPedrasSorteadas, cartelaSemRepeticao3))

154
240
157
243
149
235


## Desenvolvimento da interface do bingo:

In [ ]:
print('Bem vindo ao Bingo Hexadecimal - MENU')
while True:
    print('Aperte 1 para iniciar o bingo inserindo o nome dos jogadores.')
    print('Aperte 2 para iniciar o bingo sem inserir nome dos jogadores.')
    print('Aperte 0 para sair do programa.')
    opcao = int(input(f'Digite sua opção:\n'))
    if opcao == 0:
        print('Tchau, até mais.')
        break
    elif opcao != 1 and opcao != 2:
        print('Dígito inválido, Repita a operação.\n')
    else:
        if opcao == 1:
            nomeJogador1 = str(input(f'Jogador 1 - Qual o seu nome? \n '))
            print(f'\n Jogador 1 - {nomeJogador1}')
            print(f'Sua cartela é:{cartelaPandas1}\n')
            
            nomeJogador2 = str(input(f'Jogador 2 - Qual o seu nome? \n '))
            print(f'\n Jogador 2 - {nomeJogador2}')
            print(f'Sua cartela é:{cartelaPandas2}\n')
            
            nomeJogador3 = str(input(f'Jogador 3 - Qual o seu nome? \n '))
            print(f'\n Jogador 3 - {nomeJogador3}')
            print(f'Sua cartela é:{cartelaPandas3}\n')
        elif opcao == 2:
            print(f'\n Jogador 1')
            print(f'Sua cartela é:{cartelaPandas1}\n')
            
            print(f'\n Jogador 2')
            print(f'Sua cartela é:{cartelaPandas2}\n')
            
            print(f'\n Jogador 3')
            print(f'Sua cartela é:{cartelaPandas3}\n')
    while True:
        print(f'Insira 1 para sortear uma pedra.')
        print(f'Insira 2 para verificar a pontuação atual')
        print(f'Aperte 0 para retornar ao MENU.')
        opcao2 = int(input(f'Digite sua opção:\n'))
        
        if opcao2 == 0:
            print('Tchau, até mais.\n')
            break
        elif opcao2 != 1 and opcao2 != 2 and opcao2 != 3:
            print('Dígito inválido, repita a operação.\n')
        elif opcao2 == 1:
            pedraSorteada = sorteioPedra(lista)
            pedraHex = converterHex(pedraSorteada)
            pontuacaoJogador1 = pontuacao1(pedraSorteada)
            pontuacaoJogador2 = pontuacao2(pedraSorteada)
            pontuacaoJogador3 = pontuacao3(pedraSorteada)
            print(f'O número sorteado foi: {pedraHex}\n')
            if pontuacaoJogador1 == 16:
                premio1 = premiacao1(vetorPedrasSorteadas, cartelaSemRepeticao1)
                print(f'Parabéns Jogador 1 você é o Vencedor! ')
                print(f'Sua premiação é de: R$ {premio1} Reais ')
                break

            elif pontuacaoJogador2 == 16:
                premio2 = premiacao2(vetorPedrasSorteadas, cartelaSemRepeticao2)
                print(f'Parabéns Jogador 2 você é o Vencedor! ')
                print(f'Sua premiação é de: R$ {premio2} Reais')
                break

            elif pontuacaoJogador3 == 16:
                premio3 = premiacao3(vetorPedrasSorteadas, cartelaSemRepeticao3)
                print(f'Parabéns Jogador 3 você é o Vencedor! ')
                print(f'Sua premiação é de: R$ {premio3} Reais ')
                break    
        elif opcao2 == 2: 
            print(f'\nPONTUAÇÃO ATUAL: ')
            print(f'jogador 1: {pontuacaoJogador1}')
            print(f'jogador 2: {pontuacaoJogador2}')
            print(f'jogador 3: {pontuacaoJogador3}\n')
            